services:
    php:
        default: true
        image: tugboatqa/php:apache
        commands:
            init:

                # Install prerequisite packages
                - apt-get update
                - apt-get install -y rsync

                # Install wp-cli
                - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
                - chmod +x wp-cli.phar
                - mv wp-cli.phar /usr/local/bin/wp

                # Configure wordpress to work with tugboat
                - cp ${TUGBOAT_ROOT}/.tugboat/wp-config.tugboat.php ${TUGBOAT_ROOT}/docroot/wp-config.local.php

            update:

                # Import uploads
                - curl -L "https://www.dropbox.com/s/ufn5e3qe3sisdks/demo-wordpress-uploads.tar.gz?dl=0" > /tmp/uploads.tar.gz
                - tar -C /tmp -zxf /tmp/uploads.tar.gz
                - rsync -av --delete /tmp/uploads/ ${TUGBOAT_ROOT}/docroot/wp-content/uploads/

                # Cleanup
                - apt-get clean
                - rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

            build: |
                if [ "x${TUGBOAT_BASE_PREVIEW" != "x" ]; then
                    wp --allow-root --path=/var/www/html search-replace "${TUGBOAT_BASE_PREVIEW_URL/https?:\/\//}" "${TUGBOAT_SERVICE_URL/https?:\/\//}" --skip-columns=guid
                else
                    wp --allow-root --path=/var/www/html search-replace 'wordpress.local' "${TUGBOAT_SERVICE_URL/https?:\/\//}" --skip-columns=guid
                fi

    mysql:
        image: tugboatqa/mysql:5
        commands:
        update:
            - curl -L "https://www.dropbox.com/s/sabj5vq711bhst2/demo-wordpress-database.sql.gz?dl=0" > /tmp/database.sql.gz
            - zcat /tmp/database.sql.gz | mysql tugboat

